version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine3.18
    container_name: postgres_ecommerce
    restart: always
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    networks:
      - local
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=jl@pilgrim.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:5050'
    networks:
      - local
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local

networks:
  local: