name: CI
on: [push, pull_request]
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: build
        run: ./mvnw clean install -DskipTests